### ISSUE TITLE
don't rollback to 'inactive' replicaset

### ISSUE THREAD

**Issue by sechmann** [nais/babylon#41]
https://github.com/nais/babylon/blob/7907d96d8a62dd61abebbcd2a8e09c5762365f1b/pkg/deployment/deployment.go#L252
Here we should abort if the desired replicaset has 0 replicas.

Reasoning: We don't want to rollback to images that are not already running, only roll back when there is a replicaset already active (>0 replicas)

**Comment by sondr3** [comment]
Should we keep looping untill we find a replicaset or just set the number of replicas on the deployment to zero?

**Comment by sechmann** [comment]
looping is probably smart, i think it is possible to have "inactive" RSes between the active and the "last working RS".
If no RS is found however, set replicas to 0 on the deployment without changing the spec.
