### ISSUE TITLE
Find initial criteria for resource pruning

### ISSUE THREAD

**Issue by sondr3** [nais/babylon#7]
- [x] Document the criteria we select
- [x] Research (look on `dev-gcp`, previous projects etc)
- [x] Get NAIS to look at - and approve - what we found

**Comment by sechmann** [comment]
My thoughts:

ReplicaSets where **all** pods have one of the the following states are considered safe to scale down:
- `CreateContainerConfigError`
- `ImagePullBackOff`
- `ErrImagePull`
- `Init:CrashLoopBackOff`

Pods that have a high (thousands) number of restarts and are in `CrashLoopBackoff` or `Error` should notify the owning team, with a possibility to mute the alert

**Comment by sondr3** [comment]
@Sechmann Would be valid to also turn off pods that have been in a `ContainerCreating` for a very long time? We have a test deploy that never manages to mount a volume, so it just spins waiting for mounting forever.

**Comment by sechmann** [comment]
No, because the volume might become available at a later time, and the pods would start up (without any changes to the deployment).
The way i see it a container "stuck" in ContainerCreating waiting for a volume to become available is normal given the eventual consistency nature of k8s.
