### ISSUE TITLE
Use `alerterator` to notify teams of `babylon`

### ISSUE THREAD

**Issue by sondr3** [nais/babylon#8]
- [x] Figure out how to send alerts to `alerterator`
- [x] DEMO 👻 
- [x] We will likely have to default to the `slack-channel` of each team
- [x] Override when any existing alert-channels are available in the namespace
- [x] Allow manual override in (probably) `/teams` 
- [x] Find out if creating lots of child-alert resources or using slack web hooks??
- [x] Notify teams about which revision/containerImage to rollback

**Comment by sechmann** [comment]
doc to get you started: https://doc.nais.io/observability/alerts/

tip: start with making an alert that notifies a static channel (i.e. #babylon-alerts) before figuring out how to determine which slack channel the team wants their alerts sent to.
