### ISSUE TITLE
How do we handle state

### ISSUE THREAD

**Issue by sondr3** [nais/babylon#9]
- [ ] Is a DB even needed?
- [ ] Include NAIS people
- [ ] Should we use postgres, etcd, some other persistent storage?
- [ ] What should be stateful?
- [ ] What goes where? (annotations, storage, etc)

**Comment by sechmann** [comment]
First question is important here, there are major benefits if we can make the application stateless (or if the app can read in full state at start-up)

I imagine the primary issue is that `Events` don't live for a very long time in k8s, so looking at old `Events` without an external state is problematic. However, if the application needs old `Events` to function, it also means that something (i.e. the app) has to be up and working to persist these `Events` to the external state.

What other information are you considering storing in external state?

**Comment by sondr3** [comment]
## Notes from brainstorming sesh

- Notifications and confirmations on Slack; how do we authorize it? Connect resources with requests made on Slack.
- Can we use annotations/labels on resources?

---

We'll get back to you with some questions during the weekly :shipit:

**Comment by sondr3** [comment]
After a good session during the NAIS weekly we've decided to keep the application as stateless as possible, so we're closing this (for now).
